---
title: "Homework 1"
author: "Adam Shah"
date: "9/16/2020"
output:
  html_document: default
  pdf_document: default
---
## Problem 0
```{r}
LBO <- read.csv("LifetimeBoxOffice.csv")
str(LBO)
```
200 observations of 4 variables. 

## Problem 1
```{r}
LBO[1:10,2:3]
```
Avengers: Endgame through Frozen II

## Problem 2
```{r}
subset(LBO,subset=LifetimeGross>1e+09)
```

## Problem 3
```{r}
subset(LBO,subset=Year==2019)
```

## Problem 4
```{r}
year_df<-subset(LBO,subset=Year==2019)
gross_vec<-year_df[,3]
mean(gross_vec)
sd(gross_vec)
```
The mean is 1,183,262,439 dollars, and the standard deviation is 558,485,335 dollars. 

## Problem 5
```{r}
plot(LBO[,4],LBO[,3],main= "Lifetime Gross by Year", xlab = "Year", ylab = "Lifetime Gross (USD)")
```
On average, Lifetime Gross increases as time progresses, and movies produced in later years are more likely to appear on the top 200 list.

## Problem 6
```{r}
y <- c(1,2,1,3,4,1,1,4,2,1,3,4,3,2,1,3,4,1,2,3,1,1,2)
fac_y<-factor(y, ordered=TRUE)
levels(fac_y)<-c("Freshman","Sophomore","Junior","Senior")
fac_y
```
