---
title: "Homework 4"
author: "Adam Shah"
date: "10/14/2020"
output: html_document
---
1.
```{r}
library(ggplot2)
library(ggthemes)
austin_housing<-subset(txhousing, subset=txhousing$city=="Austin")
```

2/3.
```{r}
ggplot(austin_housing, aes(x=year, y=median))+
  geom_point()+
  labs(x="Year", y="Price", title="Figure 1: Austin median house prices by year")+
  theme_grey()
```

4.
```{r}
sanantonio_housing<-subset(txhousing,subset=txhousing$city=="San Antonio")
ggplot(sanantonio_housing, aes(x=year, y=median))+
  geom_point()+
  labs(x="Year", y="Price", title="Figure 2: San Antonio median house prices by year")+
  theme_grey()
```

5.
```{r}
ggplot(austin_housing, aes(x=year, y=median))+
  geom_point(color="red")+
  geom_point(data=sanantonio_housing, aes(x=year, y=median), color = "blue")+
  labs(x="Year", y="Price", title="Figure 3: Austin and San Antonio median house prices by year")+
  theme_grey()
```

6.
In both Austin and San Antonio, the graph shows that house prices have increased over the last 20 years, with the prices in Austin being on average higher than those in San Antonio. 