% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={QTM 220 Homework \#4},
  pdfauthor={Adam Shah},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{QTM 220 Homework \#4}
\author{Adam Shah}
\date{10/28/2021}

\begin{document}
\maketitle

\hypertarget{section}{%
\subsection{1.}\label{section}}

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\tightlist
\item
  Heteroskedasticity would invalidate the t-statistic because the
  t-statistic relies on the assumption that the variance of estimators
  given x can be expressed as a constant, sigma squared.
\item
  A high correlation coefficient between two explanatory variables does
  not matter as long as it is not 1.
\item
  Omitting an important explanatory variable would matter as it would
  violate MLR 3.
\end{enumerate}

\hypertarget{section-1}{%
\subsection{2.}\label{section-1}}

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\item
  H0: beta3-beta2=0 H1: beta3-beta2 does not equal 0
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Way 1}
\KeywordTok{data}\NormalTok{(}\StringTok{"wage2"}\NormalTok{)}
\NormalTok{fit=}\KeywordTok{lm}\NormalTok{(lwage}\OperatorTok{~}\NormalTok{educ}\OperatorTok{+}\NormalTok{exper}\OperatorTok{+}\NormalTok{tenure, }\DataTypeTok{data=}\NormalTok{wage2)}
\KeywordTok{summary}\NormalTok{(fit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = lwage ~ educ + exper + tenure, data = wage2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.8282 -0.2401  0.0203  0.2569  1.3400 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 5.496696   0.110528  49.731  < 2e-16 ***
## educ        0.074864   0.006512  11.495  < 2e-16 ***
## exper       0.015328   0.003370   4.549 6.10e-06 ***
## tenure      0.013375   0.002587   5.170 2.87e-07 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.3877 on 931 degrees of freedom
## Multiple R-squared:  0.1551, Adjusted R-squared:  0.1524 
## F-statistic: 56.97 on 3 and 931 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit}\OperatorTok{$}\NormalTok{coefficients[}\DecValTok{3}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      exper 
## 0.01532847
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit}\OperatorTok{$}\NormalTok{coefficients[}\DecValTok{4}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    tenure 
## 0.0133748
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{B3_B2=}\StringTok{ }\NormalTok{fit}\OperatorTok{$}\NormalTok{coefficients[}\DecValTok{4}\NormalTok{]}\OperatorTok{-}\NormalTok{fit}\OperatorTok{$}\NormalTok{coefficients[}\DecValTok{3}\NormalTok{]}
\NormalTok{B3_B2 }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       tenure 
## -0.001953674
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{vcov}\NormalTok{(fit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               (Intercept)          educ         exper        tenure
## (Intercept)  1.221649e-02 -6.776256e-04 -2.514230e-04 -3.009699e-06
## educ        -6.776256e-04  4.241200e-05  1.011506e-05 -1.460449e-06
## exper       -2.514230e-04  1.011506e-05  1.135402e-05 -2.226217e-06
## tenure      -3.009699e-06 -1.460449e-06 -2.226217e-06  6.693578e-06
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{se_B3_B2=}\KeywordTok{sqrt}\NormalTok{(}\KeywordTok{vcov}\NormalTok{(fit)[}\DecValTok{3}\NormalTok{,}\DecValTok{3}\NormalTok{]}\OperatorTok{+}\KeywordTok{vcov}\NormalTok{(fit)[}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{]}\OperatorTok{-}\DecValTok{2}\OperatorTok{*}\KeywordTok{vcov}\NormalTok{(fit)[}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{]) }

\NormalTok{t2=B3_B2}\OperatorTok{/}\NormalTok{se_B3_B2}
\NormalTok{t2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     tenure 
## -0.4118703
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sig=}\FloatTok{0.05}
\NormalTok{critical_val=}\KeywordTok{qt}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{sig}\OperatorTok{/}\DecValTok{2}\NormalTok{,}\DataTypeTok{df=}\NormalTok{fit}\OperatorTok{$}\NormalTok{df.residual) }
\NormalTok{lower=B3_B2}\OperatorTok{-}\NormalTok{critical_val}\OperatorTok{*}\NormalTok{se_B3_B2}
\NormalTok{upper=B3_B2}\OperatorTok{+}\NormalTok{critical_val}\OperatorTok{*}\NormalTok{se_B3_B2}
\KeywordTok{sprintf}\NormalTok{(}\StringTok{"95 percent confidence= [%.3f %.3f]"}\NormalTok{, lower, upper)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "95 percent confidence= [-0.011 0.007]"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Way 2}
\NormalTok{wage2}\OperatorTok{$}\NormalTok{theta=wage2}\OperatorTok{$}\NormalTok{exper}\OperatorTok{+}\NormalTok{wage2}\OperatorTok{$}\NormalTok{tenure  }
\NormalTok{new_fit<-}\KeywordTok{lm}\NormalTok{(lwage}\OperatorTok{~}\NormalTok{educ}\OperatorTok{+}\NormalTok{theta}\OperatorTok{+}\NormalTok{tenure,}\DataTypeTok{data=}\NormalTok{wage2) }
\KeywordTok{summary}\NormalTok{(new_fit) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = lwage ~ educ + theta + tenure, data = wage2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.8282 -0.2401  0.0203  0.2569  1.3400 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  5.496696   0.110528  49.731  < 2e-16 ***
## educ         0.074864   0.006512  11.495  < 2e-16 ***
## theta        0.015328   0.003370   4.549  6.1e-06 ***
## tenure      -0.001954   0.004743  -0.412    0.681    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.3877 on 931 degrees of freedom
## Multiple R-squared:  0.1551, Adjusted R-squared:  0.1524 
## F-statistic: 56.97 on 3 and 931 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{confint}\NormalTok{(new_fit,}\StringTok{'tenure'}\NormalTok{,}\DataTypeTok{level=}\FloatTok{0.95}\NormalTok{, }\DataTypeTok{df=}\NormalTok{fit}\OperatorTok{$}\NormalTok{df.residual)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              2.5 %     97.5 %
## tenure -0.01126271 0.00735536
\end{verbatim}

\hypertarget{section-2}{%
\subsection{3.}\label{section-2}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{data}\NormalTok{(}\StringTok{"k401ksubs"}\NormalTok{)}
\NormalTok{Q3 <-}\StringTok{ }\NormalTok{k401ksubs[k401ksubs}\OperatorTok{$}\NormalTok{fsize}\OperatorTok{==}\DecValTok{1}\NormalTok{,] }
\NormalTok{fit=}\KeywordTok{lm}\NormalTok{(nettfa}\OperatorTok{~}\NormalTok{inc}\OperatorTok{+}\NormalTok{age, }\DataTypeTok{data=}\NormalTok{Q3) }
\KeywordTok{summary}\NormalTok{(fit) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = nettfa ~ inc + age, data = Q3)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -179.95  -14.16   -3.42    6.03 1113.94 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -43.03981    4.08039 -10.548   <2e-16 ***
## inc           0.79932    0.05973  13.382   <2e-16 ***
## age           0.84266    0.09202   9.158   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 44.68 on 2014 degrees of freedom
## Multiple R-squared:  0.1193, Adjusted R-squared:  0.1185 
## F-statistic: 136.5 on 2 and 2014 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{coef}\NormalTok{(fit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)         inc         age 
## -43.0398119   0.7993167   0.8426563
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{coef}\NormalTok{(}\KeywordTok{summary}\NormalTok{(fit))[, }\DecValTok{2}\NormalTok{][}\DecValTok{3}\NormalTok{] }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        age 
## 0.09201685
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sig=}\FloatTok{0.01}
\NormalTok{crit=}\KeywordTok{qt}\NormalTok{(sig,}\DataTypeTok{df=}\NormalTok{fit}\OperatorTok{$}\NormalTok{df.residual)}
\NormalTok{crit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -2.328201
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{t3 <-}\StringTok{ }\NormalTok{(fit}\OperatorTok{$}\NormalTok{coefficients[}\DecValTok{3}\NormalTok{] }\OperatorTok{-}\StringTok{ }\DecValTok{1}\NormalTok{) }\OperatorTok{/}\StringTok{ }\KeywordTok{coef}\NormalTok{(}\KeywordTok{summary}\NormalTok{(fit))[, }\DecValTok{2}\NormalTok{][}\DecValTok{3}\NormalTok{]}
\NormalTok{t3}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       age 
## -1.709944
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{pnorm}\NormalTok{(t3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        age 
## 0.04363813
\end{verbatim}

We fail to reject H0 at 1\% significance- the p-value was 0.0436, which
is greater than 0.01.

\hypertarget{section-3}{%
\subsection{4.}\label{section-3}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#ii}
\KeywordTok{data}\NormalTok{(}\StringTok{"discrim"}\NormalTok{)}
\NormalTok{discrim2 <-}\StringTok{ }\NormalTok{discrim[,}\KeywordTok{c}\NormalTok{(}\StringTok{'prpblck'}\NormalTok{, }\StringTok{'prppov'}\NormalTok{)]}
\NormalTok{discrim2}\OperatorTok{$}\NormalTok{lpsoda <-}\StringTok{ }\KeywordTok{log}\NormalTok{(discrim}\OperatorTok{$}\NormalTok{psoda)}
\NormalTok{discrim2}\OperatorTok{$}\NormalTok{lincome <-}\StringTok{ }\KeywordTok{log}\NormalTok{(discrim}\OperatorTok{$}\NormalTok{income)}
\KeywordTok{cor.test}\NormalTok{(discrim2}\OperatorTok{$}\NormalTok{prppov, discrim2}\OperatorTok{$}\NormalTok{lincome) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  discrim2$prppov and discrim2$lincome
## t = -31.04, df = 407, p-value < 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.8650980 -0.8071224
## sample estimates:
##       cor 
## -0.838467
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit=}\KeywordTok{lm}\NormalTok{(lpsoda}\OperatorTok{~}\NormalTok{prpblck}\OperatorTok{+}\NormalTok{lincome}\OperatorTok{+}\NormalTok{prppov, }\DataTypeTok{data=}\NormalTok{discrim2)}
\KeywordTok{summary}\NormalTok{(fit) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = lpsoda ~ prpblck + lincome + prppov, data = discrim2)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.32218 -0.04648  0.00651  0.04272  0.35622 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -1.46333    0.29371  -4.982  9.4e-07 ***
## prpblck      0.07281    0.03068   2.373   0.0181 *  
## lincome      0.13696    0.02676   5.119  4.8e-07 ***
## prppov       0.38036    0.13279   2.864   0.0044 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.08137 on 397 degrees of freedom
##   (9 observations deleted due to missingness)
## Multiple R-squared:  0.08696,    Adjusted R-squared:  0.08006 
## F-statistic:  12.6 on 3 and 397 DF,  p-value: 6.917e-08
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{coef}\NormalTok{(}\KeywordTok{summary}\NormalTok{(fit))[, }\DecValTok{3}\NormalTok{][}\DecValTok{4}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   prppov 
## 2.864364
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{2}\OperatorTok{*}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\KeywordTok{pnorm}\NormalTok{(}\KeywordTok{coef}\NormalTok{(}\KeywordTok{summary}\NormalTok{(fit))[, }\DecValTok{3}\NormalTok{][}\DecValTok{4}\NormalTok{]))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      prppov 
## 0.004178478
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{coef}\NormalTok{(}\KeywordTok{summary}\NormalTok{(fit))[, }\DecValTok{3}\NormalTok{][}\DecValTok{3}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## lincome 
## 5.11878
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{2}\OperatorTok{*}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\KeywordTok{pnorm}\NormalTok{(}\KeywordTok{coef}\NormalTok{(}\KeywordTok{summary}\NormalTok{(fit))[, }\DecValTok{3}\NormalTok{][}\DecValTok{3}\NormalTok{]))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     lincome 
## 3.07518e-07
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#iii}
\NormalTok{discrim2}\OperatorTok{$}\NormalTok{lhseval <-}\StringTok{ }\KeywordTok{log}\NormalTok{(discrim}\OperatorTok{$}\NormalTok{hseval)}
\NormalTok{fit2=}\KeywordTok{lm}\NormalTok{(lpsoda}\OperatorTok{~}\NormalTok{prpblck}\OperatorTok{+}\NormalTok{lincome}\OperatorTok{+}\NormalTok{prppov}\OperatorTok{+}\NormalTok{lhseval, }\DataTypeTok{data=}\NormalTok{discrim2)}
\KeywordTok{summary}\NormalTok{(fit2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = lpsoda ~ prpblck + lincome + prppov + lhseval, data = discrim2)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.30652 -0.04380  0.00701  0.04332  0.35272 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -0.84151    0.29243  -2.878 0.004224 ** 
## prpblck      0.09755    0.02926   3.334 0.000937 ***
## lincome     -0.05299    0.03753  -1.412 0.158706    
## prppov       0.05212    0.13450   0.388 0.698571    
## lhseval      0.12131    0.01768   6.860 2.67e-11 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.07702 on 396 degrees of freedom
##   (9 observations deleted due to missingness)
## Multiple R-squared:  0.1839, Adjusted R-squared:  0.1757 
## F-statistic: 22.31 on 4 and 396 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{coef}\NormalTok{(}\KeywordTok{summary}\NormalTok{(fit2))[, }\DecValTok{3}\NormalTok{][}\DecValTok{5}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  lhseval 
## 6.859601
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{2}\OperatorTok{*}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\KeywordTok{pnorm}\NormalTok{(}\KeywordTok{coef}\NormalTok{(}\KeywordTok{summary}\NormalTok{(fit2))[, }\DecValTok{3}\NormalTok{][}\DecValTok{5}\NormalTok{]))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      lhseval 
## 6.905365e-12
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#iv}
\KeywordTok{coef}\NormalTok{(}\KeywordTok{summary}\NormalTok{(fit2))[, }\DecValTok{3}\NormalTok{][}\DecValTok{4}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   prppov 
## 0.387532
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{2}\OperatorTok{*}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\KeywordTok{pnorm}\NormalTok{(}\KeywordTok{coef}\NormalTok{(}\KeywordTok{summary}\NormalTok{(fit2))[, }\DecValTok{3}\NormalTok{][}\DecValTok{4}\NormalTok{]))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    prppov 
## 0.6983624
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{coef}\NormalTok{(}\KeywordTok{summary}\NormalTok{(fit))[, }\DecValTok{3}\NormalTok{][}\DecValTok{3}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## lincome 
## 5.11878
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{2}\OperatorTok{*}\NormalTok{(}\KeywordTok{pnorm}\NormalTok{(}\KeywordTok{coef}\NormalTok{(}\KeywordTok{summary}\NormalTok{(fit))[, }\DecValTok{3}\NormalTok{][}\DecValTok{3}\NormalTok{]))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## lincome 
##       2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{restricted=}\KeywordTok{lm}\NormalTok{(lpsoda}\OperatorTok{~}\NormalTok{prpblck}\OperatorTok{+}\NormalTok{lhseval, }\DataTypeTok{data=}\NormalTok{discrim2) }
\NormalTok{unrestricted=}\KeywordTok{lm}\NormalTok{(lpsoda}\OperatorTok{~}\NormalTok{prpblck}\OperatorTok{+}\NormalTok{lincome}\OperatorTok{+}\NormalTok{prppov}\OperatorTok{+}\NormalTok{lhseval, }\DataTypeTok{data=}\NormalTok{discrim2) }
\NormalTok{ssr_rest=}\KeywordTok{sum}\NormalTok{(restricted}\OperatorTok{$}\NormalTok{residuals}\OperatorTok{^}\DecValTok{2}\NormalTok{)}
\NormalTok{ssr_unrest=}\KeywordTok{sum}\NormalTok{(unrestricted}\OperatorTok{$}\NormalTok{residuals}\OperatorTok{^}\DecValTok{2}\NormalTok{)}
\NormalTok{F4=((ssr_rest}\OperatorTok{-}\NormalTok{ssr_unrest)}\OperatorTok{/}\DecValTok{2}\NormalTok{)}\OperatorTok{/}\NormalTok{(ssr_unrest}\OperatorTok{/}\NormalTok{unrestricted}\OperatorTok{$}\NormalTok{df.residual) }
\NormalTok{F4}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.522687
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{qf}\NormalTok{(}\FloatTok{0.95}\NormalTok{ , }\DataTypeTok{df1=}\DecValTok{2}\NormalTok{, }\DataTypeTok{df2=}\NormalTok{unrestricted}\OperatorTok{$}\NormalTok{df.residual)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.01851
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{1}\OperatorTok{-}\KeywordTok{pf}\NormalTok{(F4, }\DataTypeTok{df1=}\DecValTok{2}\NormalTok{, }\DataTypeTok{df2=}\NormalTok{unrestricted}\OperatorTok{$}\NormalTok{df.residual)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.03044854
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{1}
\item
  prppov and lincome have a correlation of -0.838, and both have
  statistically significant p-values- prppov has a two-sided p-value of
  0.00418, and lincome has a p-value of 3.07e-7. The correlation between
  prpblck and lincome is -0.838467.
\item
  The beta coefficient of lhseval demonstrates that soda increases by
  0.12 percent for each percent increase in hseval. This variable has a
  statistically significant p-value of 6.91e-12.
\item
  The p-values of both variables increased, meaning that their
  individual statistical significance decreased. They are jointly
  significant- F was 3.52 with the critical value for 95\% significance
  at 3.02, and the p-value was 0.0304. However, the joint significance
  has decreased, most likely due to the high correlation between lhseval
  and lincome as well as prppov. Much of the variation in lpsoda due to
  lhseval was still accounted for by the other two variables when
  absent, but lhseval's inclusion lowers the significance of prppov and
  lincome.
\end{enumerate}

\end{document}
